### ISSUE TITLE
Hinweise-Funktion wie Anking-Notetype Addon

### ISSUE THREAD

**Issue by Taddellos** [ProjektAnkiBVMD/notetype-addon#2]
Hallo, ich würde mich sehr über eine Hinweisfunktion per Tasten-Shortcut wie es mit dem Notiztypen des Anking geht freuen.
Oder geht das vielleicht jetzt schon einfach über das vorzeitige manuelle Aufdecken eines Feldes?
Danke für das tolle Projekt!

**Comment by ysaid22** [comment]
Hallo ich kann mit meinem Ankicontroller nicht scrollen. Ich habe versucht den Code "#qa #container { overflow-y: unset !important; }" hinzufügen aber es Zeigt immer Fehler : 

Anki 24.06.3 (d678e393)  (ao)
Python 3.9.18 Qt 6.6.2 PyQt 6.6.1
Platform: macOS-14.7.1-x86_64-i386-64bit

Traceback (most recent call last):
  File "/Users/youssefyoussef/Library/Application Support/Anki2/addons21/2058530482/ankiaddonconfig/window.py", line 325, in on_editing_finished
    self.conf.set(key, line_edit.text())
  File "/Users/youssefyoussef/Library/Application Support/Anki2/addons21/2058530482/ankiaddonconfig/manager.py", line 78, in set
    hook(key, value)
  File "/Users/youssefyoussef/Library/Application Support/Anki2/addons21/2058530482/notetype_setting.py", line 73, in update_all
    conf.config_window.update_widgets()
  File "/Users/youssefyoussef/Library/Application Support/Anki2/addons21/2058530482/ankiaddonconfig/window.py", line 95, in update_widgets
    widget_update()
  File "/Users/youssefyoussef/Library/Application Support/Anki2/addons21/2058530482/ankiaddonconfig/window.py", line 434, in update
    set_color(value)
  File "/Users/youssefyoussef/Library/Application Support/Anki2/addons21/2058530482/ankiaddonconfig/window.py", line 425, in set_color
    color.setNamedColor(rgb)
TypeError: setNamedColor(self, name: str): argument 1 has unexpected type 'NoneType'

===Add-ons (active)===
(add-on provided name [Add-on folder, installed at, version, is config changed])
AMBOSS add-on ['0amboss_addon', 2024-08-05T16:24, 'None', '']
Ankizin Notetypes - ehem ProjektAnki ['2058530482', 2024-10-02T17:24, 'None', mod]
Colorful Tags  Hierarchical Tags ['594329229', 2022-09-15T17:06, 'None', '']
Contanki - Controller Support for Anki beta ['1898790263', 2024-03-01T02:22, 'v1.0.2', '']
Filtered Deck From Tag ['2058067048', 2023-02-19T02:42, 'None', '']
Image Occlusion Enhanced ['1374772155', 2022-04-09T09:15, 'None', '']
Opening the same window multiple time ['354407385', 2023-11-05T02:59, 'None', '']
Review Heatmap ['1771074083', 2022-06-30T03:43, 'None', '']
Special Fields ['1102281552', 2024-10-26T17:51, 'None', mod]

===IDs of active AnkiWeb add-ons===
1102281552 1374772155 1771074083 1898790263 2058067048 2058530482 354407385 594329229

===Add-ons (inactive)===
(add-on provided name [Add-on folder, installed at, version, is config changed])
